// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5V3errwOnk8JMxhxao2PQite21Qww6xU',
    appId: '1:45604422789:web:21a247d37f0270c37d55ec',
    messagingSenderId: '45604422789',
    projectId: 'getmemberapp',
    authDomain: 'getmemberapp.firebaseapp.com',
    storageBucket: 'getmemberapp.firebasestorage.app',
    measurementId: 'G-GF4GKW5W9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYlOlv2hGpl0NWoZZ4BOVNEMwSUh-AJk',
    appId: '1:45604422789:android:6c7ae9d79f1dcaa87d55ec',
    messagingSenderId: '45604422789',
    projectId: 'getmemberapp',
    storageBucket: 'getmemberapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyruqky4Ri-ToGixyp_6AvwpRiwx6ws1Y',
    appId: '1:45604422789:ios:2194cd93bfa40f5a7d55ec',
    messagingSenderId: '45604422789',
    projectId: 'getmemberapp',
    storageBucket: 'getmemberapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyruqky4Ri-ToGixyp_6AvwpRiwx6ws1Y',
    appId: '1:45604422789:ios:2194cd93bfa40f5a7d55ec',
    messagingSenderId: '45604422789',
    projectId: 'getmemberapp',
    storageBucket: 'getmemberapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5V3errwOnk8JMxhxao2PQite21Qww6xU',
    appId: '1:45604422789:web:526e640cdbcab4887d55ec',
    messagingSenderId: '45604422789',
    projectId: 'getmemberapp',
    authDomain: 'getmemberapp.firebaseapp.com',
    storageBucket: 'getmemberapp.firebasestorage.app',
    measurementId: 'G-9LR89YS1LX',
  );

}